version: '3'

services:
  db:
    image: postgres
    container_name: db_container
    restart: always
    environment:
      POSTGRES_PASSWORD: CT5SAihFkG0RIBkyuAkH8G_61k9UPSMa
      POSTGRES_USER: yrnozpvn
      POSTGRES_DB: yrnozpvn
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
